openapi: 3.0.1
info:
  title: Rust SQL Server CRUD API
  version: 1.0.0
paths:
  /api/pessoas:
    get:
      summary: Get all pessoas
      responses:
        '200':
          description: A list of pessoas
    post:
      summary: Create a new pessoa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pessoa'
      responses:
        '201':
          description: The created pessoa
  /api/pessoas/{id}:
    get:
      summary: Get a pessoa by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: A single pessoa
        '404':
          description: Pessoa not found
    put:
      summary: Update a pessoa by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pessoa'
      responses:
        '200':
          description: The updated pessoa
    delete:
      summary: Delete a pessoa by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: No Content
components:
  schemas:
    Pessoa:
      type: object
      required:
        - nome
        - email
      properties:
        id:
          type: string
          format: uuid
        nome:
          type: string
        email:
          type: string
